### ISSUE TITLE
use setContent to specify what content the plugin provides on each level

### ISSUE THREAD

**Issue by MartijnKaijser** [romanvm/plugin.video.example#6]
We see a lot of plugins not properly setting content on each level. This makes it really hard for skinners to give a proper display of content.
http://mirrors.kodi.tv/docs/python-docs/15.x-isengard/xbmcplugin.html#-setContent
provides a way to define what each list represents and as such also sets the correct viewtype and infopanel layout.
If you could add this to the example that would be great :)

**Comment by romanvm** [comment]
Honestly, I don't see where this fit in my example, because it does not provide any of the content that can be set with `setContent` method. Also, I intended this as a very basic example that provides just enough info to get you started, and don't like the idea of bloating it with extra features trying to cover all possible scenarios, which is still a futile task IMO. So I'd like to stick to simplicity rather than to "cover it all" principle.

**Comment by MartijnKaijser** [comment]
just to return on this :)
With v17 new default skin it's kind of mandatory this will be set else you wont get a correct view.

**Comment by romanvm** [comment]
Estuary provides reasonable views (Icons and WideList) for generic videos. IMO, it's enough to get you started. If someone wants to use additional views to show extended info (after all, it's what those additional views are for), they can dig into the documentation and implement it by themselves.
